version: '3.9'
services:
  postgresql:
    image: postgres:15
    container_name: links_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: scrapper
    env_file: ['.env']
    networks: ['backend']
    volumes:
      - links_db:/var/lib/postgresql/data

  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on: ['postgresql']
    command:
      - --hub-mode=off
      - --changelog-file=master.xml
      - --url=jdbc:postgresql://postgresql:5432/scrapper
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    env_file: ['.env']
    volumes:
      - ./migrations:/liquibase/changelog
    networks: ['backend']

volumes:
  links_db:

networks:
  backend: