springdoc:
  swagger-ui:
    path: /swagger-ui


app:
  scheduler:
    interval: 60s
    maxLinkAge: 120s
  github:
    baseUrl: https://api.github.com
  stackoverflow:
    baseUrl: https://api.stackexchange.com/2.3
  bot:
    baseUrl: http://localhost:8081
  database-access-type: jpa
  queue:
    queueName: tcs.queue
    exchangeName: tcs.exchange
    routing-key: tcs

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
