/*
 * This file is generated by jOOQ.
 */
package ru.tinkoff.edu.java.scrapper.domain.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Configuration;

import ru.tinkoff.edu.java.scrapper.domain.jooq.routines.ClearUnusedChats;
import ru.tinkoff.edu.java.scrapper.domain.jooq.routines.ClearUnusedLinks;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.17.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.clear_unused_chats</code>
     */
    public static void clearUnusedChats(
          Configuration configuration
    ) {
        ClearUnusedChats p = new ClearUnusedChats();

        p.execute(configuration);
    }

    /**
     * Call <code>public.clear_unused_links</code>
     */
    public static void clearUnusedLinks(
          Configuration configuration
    ) {
        ClearUnusedLinks p = new ClearUnusedLinks();

        p.execute(configuration);
    }
}
