on:
  push:
    paths:
      - 'bot/**'
      - 'bot.Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - run: mvn package -pl bot -am
      - uses: actions/upload-artifact@v3
        with:
          name: bot.jar
          path: bot/target/bot-*.jar
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: wani4ka/tcs-edu-task:bot
          file: bot.Dockerfile