on:
  push:
    paths:
      - 'bot/**'
      - '.github/workflows/bot.yml'
      - 'link-parser/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: temurin
          cache: maven
      - name: Validate code style
        run: mvn -pl bot -am checkstyle:check
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: temurin
          cache: maven
      - name: Compile project
        run: mvn package -pl bot -am
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bot.jar
          path: bot/target/bot-*.jar
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Store required variables
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> ${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/tcs-edu-bot:${{ env.BRANCH_NAME }}
          context: bot
