on:
  push:
    paths:
      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - run: mvn package -pl scrapper -am
      - uses: actions/upload-artifact@v3
        with:
          name: scrapper.jar
          path: scrapper/target/scrapper-*.jar