on:
  push:
#    paths:
#      - 'scrapper/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - run: mvn package -pl scrapper -am
      - uses: actions/upload-artifact@v3
        with:
          name: scrapper.jar
          path: scrapper/target/scrapper-*.jar
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: wani4ka/tcs-edu-task:scrapper
          file: scrapper.Dockerfile