on:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper.Dockerfile'
      - '.github/workflows/scrapper.yml'
      - 'link-parser/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Validate code style
        run: mvn -pl scrapper -am checkstyle:check
  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - name: Compile project
        run: mvn package -pl scrapper -am
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: scrapper.jar
          path: scrapper/target/scrapper-*.jar
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: 'ghcr.io/${OWNER,,}/tcs-edu-scrapper:latest'
          file: scrapper.Dockerfile
        env:
          OWNER: ${{ github.repository_owner }}
