on:
  push:
    paths:
      - 'scrapper/**'
      - 'scrapper.Dockerfile'
      - '.github/workflows/scrapper.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: temurin
          cache: maven
      - run: mvn package -pl scrapper -am
      - name: Validate code style
        run: mvn -pl scrapper -am checkstyle:check
      - uses: actions/upload-artifact@v3
        with:
          name: scrapper.jar
          path: scrapper/target/scrapper-*.jar
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/wani4ka/tcs-edu-scrapper:latest
          file: scrapper.Dockerfile
